### ISSUE TITLE
files/client.go Upload error

### ISSUE THREAD

**Issue by wedy** [FlatFilers/flatfile-go#5]
hi there,

I am using this files/client.go Upload(), it seems when we write the Body, the value gets wrapped by extra "
I suspected the func WriteMultipartJSON when we Marshal it, it does this

the error that I am getting as below the extra \" ... \" I think it's the culprit, I wonder if anyone can help with this, If not, I am more than happy to contribute on this part, thank you

```
{
    "errors": [
        {
            "key": "/v1/files",
            "message": "You must provide an alphanumeric + underscore string. Provided ID: \"us_env-8SO5cXX\""
        }
    ]
}
```

I think the problem is on this

```
func WriteMultipartJSON(writer *multipart.Writer, field string, value interface{}) error {
	bytes, err := json.Marshal(value)
	if err != nil {
		return err
	}
	return writer.WriteField(field, string(bytes))
}
```
where the value is `string` already, and json.Marshal will converts the string values (which are already JSON-compatible) into JSON strings.

where I think, it should be something like 

```
func WriteMultipartString(writer *multipart.Writer, field string, value string) error {
    return writer.WriteField(field, strValue) 
}
```

**Comment by wmwassmann-gh** [comment]
Hey Wedy! The error that you're getting there indicates that the environment string you provided is not formatted correctly - in this case the dash should be replaced by an underscore. Can you try reformatting the environment value to be 'us_env_8SO5cXX'?

**Comment by wedy** [comment]
thanks for the response @wmwassman-gh

oh apologise, when I wrote the error, I changed the error text on purpose, since I didn't want to share the right envID, I accidentally put "-" in there when I was trying to redact the value

the error that I've got was something like this (it's underscore, not hyphen)

```
{
    "errors": [
        {
            "key": "/v1/files",
            "message": "You must provide an alphanumeric + underscore string. Provided ID: \"us_env_XXXX\""
        }
    ]
}
```

so I think the issue still there, since we pass string "us_env_XXXX" value to `WriteMultipartJSON`, it's trying to Marshall the string, hence the extra \" \"

**Comment by wmwassmann-gh** [comment]
We just pushed out an update to our SDk that we're hoping will help, and should provide more details about the cause of the error if not. Would you be able to test again using v 0.0.21?

**Comment by wedy** [comment]
thank you @wmwassmann-gh, will pull it and give it a try, we will let you know and thank you again for quick turnaround 👍

**Comment by wedy** [comment]
hi @wmwassmann-gh, I think the issue still there, I think the code here still Marshalling String which adding extra "" https://github.com/FlatFilers/flatfile-go/blob/main/internal/multipart.go#L83

maybe I am not using it right, let me share what I have done

```
	flatFileRequest := &flatfile.CreateFileRequest{
		SpaceId:       "us_sp_test",
		EnvironmentId: "us_env_test",
	}
	_, err := f.client.Files.Upload(ctx, file, flatFileRequest)
```

in https://github.com/FlatFilers/flatfile-go/blob/main/files/client.go#L110
we do 
```
if err := writer.WriteJSON("environmentId", request.EnvironmentId); err != nil {
		return nil, err
	}
```

in the WriteJSON params the request.EnvironmentId is a string
https://github.com/FlatFilers/flatfile-go/blob/main/internal/multipart.go#L83

```
// WriteJSON writes the given value as a JSON form field.
func (w *MultipartWriter) WriteJSON(
	field string,
	value interface{},
	opts ...WriteMultipartOption,
) error {
	bytes, err := json.Marshal(value)
	if err != nil {
		return err
	}
	return w.WriteField(field, string(bytes), opts...)
}
```
and since we json.Marshal("us_sp_test") it returns extra `\" \"`, I hope this code can explain my theory on this https://go.dev/play/p/J6FwBga7-7x 

thank you again for quick response on this

**Comment by wmwassmann-gh** [comment]
Thank you for all those details! We just pushed out a patch to address this - could you update to v0.0.22 and let me know if your requests are successful with that?

**Comment by wedy** [comment]
thank you again @wmwassmann-gh, I think the patch of https://github.com/FlatFilers/flatfile-go/pull/6/files will definitely fix the problem, however, it 0.0.22, the patch is not in there https://github.com/FlatFilers/flatfile-go/blob/v0.0.22/files/client.go

**Comment by wmwassmann-gh** [comment]
I'm so sorry, it looks like the patch we made didn't actually make it into the update. Please try again with 0.0.23. Thank you so much for bearing with us!

**Comment by wedy** [comment]
it works thank you @wmwassmann-gh , I am going to close this issue, thank you again for your help
